/**
 */
'use strict';
/**
 * 进行定义请求Action类型
 */

//在线新闻
export const ACTION_ONLINE_NEWS_PRE_FETCH = 'ACTION_ONLINE_NEWS_PRE_FETCH';
export const ACTION_ONLINE_NEWS_FETCH_OK = 'ACTION_ONLINE_NEWS_FETCH_OK';
export const ACTION_ONLINE_NEWS_FETCH_ERROR = 'ACTION_ONLINE_NEWS_FETCH_ERROR';

//微信精选（分页加载）
export const ACTION_WEIXIN_NEWS_PRE_FETCH = 'ACTION_WEIXIN_NEWS_PRE_FETCH';
export const ACTION_WEIXIN_NEWS_FETCH_OK = 'ACTION_WEIXIN_NEWS_FETCH_OK';
export const ACTION_WEIXIN_NEWS_FETCH_ERROR = 'ACTION_WEIXIN_NEWS_FETCH_ERROR';

//Home页top banner
export const ACTION_HOME_BANNER_FETCHED = 'ACTION_HOME_BANNER_FETCHED';

//Home页news分类
export const ACTION_HOME_NEWS_CATEGORY_FETCHED = 'ACTION_HOME_NEWS_CATEGORY_FETCHED';

//Home万年历
export const ACTION_WNL_FETCHED = 'ACTION_WNL_FETCHED';

//Home页最近影讯
export const ACTION_RECENT_MOVIES_FETCHED = 'ACTION_RECENT_MOVIES_FETCHED';

//问答机器人
export const ACTION_CHART_ROBOT_PRE_FETCH = 'ACTION_CHART_ROBOT_PRE_FETCH';
export const ACTION_CHART_ROBOT_FETCH_OK = 'ACTION_CHART_ROBOT_FETCH_OK';
export const ACTION_CHART_ROBOT_FETCH_ERROR = 'ACTION_CHART_ROBOT_FETCH_ERROR';